###########
# site.title

title: AlexVagrant Blog
description: ""
# baseurl: "/jekyllBear" # the subpath of your site, e.g. /blog/
url: "https://alexvagrant.github.io/" # the base hostname & protocol for your site
# host: 0.0.0.0


#########################
# more settings

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

#baseurl: ""
# permalink: /blog/:slug
timezone: Asia/Shanghai
future: true

exclude:
- README.md
- LICENSE.md

exclude: [vendor]

About: /about

# Add general links to site pages here
links:
  Resume: /assets/resume.pdf
  

# Add links for more focus here
special_links:
  "Search": https://duckduckgo.com

sass:
  sass_dir: _sass
  style:    compressed

#theme_config:
#  appearance: "auto" # can be "light", "dark" or "auto"
#  back_home_text: ".." # customize text for homepage link in post layout
#  date_format: "%Y-%m-%d" # customize how date is formatted
#  show_description: false # show blog description in home page
