
title: AlexVagrant Blog
email: 1113629699@qq.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 我是谁?
github_username:  AlexVagrant

# Build settings
theme: minima
#theme: jekyll-theme-minimal
#theme: no-style-please
plugins:
  - jekyll-feed

